<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Acr.UserDialogs" Version="7.2.0.564" />
    <PackageReference Include="IdentityModel" Version="3.10.10" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="PCLCrypto" Version="2.0.147" />
    <PackageReference Include="SlideOverKit" Version="2.1.6.2" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="4.7.0" />
    <PackageReference Include="Xamarin.FFImageLoading.Forms" Version="2.4.11.982" />
    <PackageReference Include="Xamarin.Forms" Version="4.8.0.1821" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Permissions\" />
    <Folder Include="Models\Permissions\" />
  </ItemGroup>
</Project>
