version: '3.4'

services:
  sql-data-test:
    image: mcr.microsoft.com/mssql/server:2017-latest@sha256:0ee8b0ae2e442b7f58a2813456d9d9e6e8923c140200672cf8683bbc6b88386d 

  nosql-data-test:
    image: mongo@sha256:cc62438c8ef61ce02f89b4f7c026e735df4580e8cd8857980d12e0eae73bf044

  basket-data-test:
    image: redis:alpine@sha256:f773b35a95e170d92dd4214a3ec4859b1b7960bf56896ae687646d695f311187

  rabbitmq-test:
    image: rabbitmq:3-management-alpine@sha256:878d4697c9c7dded8458670adaff1e45a9c2bc19c7e82d1a06b8a70adfc76142

  identity-api-test:
    image: ${REGISTRY:-eshop}/identity-api-test:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    depends_on:
      - sql-data-test

  basket-api-functional-test:
    image: ${REGISTRY:-eshop}/basket-api-test:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
      target: functionaltest
    depends_on:
      - basket-data-test
      - identity-api-test
      - rabbitmq-test
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests

  basket-api-unit-test:
    image: ${REGISTRY:-eshop}/basket-api-unit-test:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
      target: unittest
    depends_on:
      - basket-data-test
      - identity-api-test
      - rabbitmq-test
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests

  catalog-api-functional-test:
    image: ${REGISTRY:-eshop}/catalog-api-functional-test:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
      target: functionaltest
    depends_on:
      - sql-data-test
      - rabbitmq-test
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests

  catalog-api-unit-test:
    image: ${REGISTRY:-eshop}/catalog-api-unit-test:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
      target: unittest
    depends_on:
      - sql-data-test
      - rabbitmq-test
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests

  ordering-api-functional-test:
    image: ${REGISTRY:-eshop}/ordering-api-test:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
      target: functionaltest
    depends_on:
      - sql-data-test
      - rabbitmq-test
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests

  ordering-api-unit-test:
    image: ${REGISTRY:-eshop}/ordering-api-unit-test:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
      target: unittest
    depends_on:
      - sql-data-test
      - rabbitmq-test
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests

  marketing-api-functional-test:
    image: ${REGISTRY:-eshop}/marketing-api-test:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Marketing/Marketing.API/Dockerfile
      target: functionaltest
    depends_on:
      - sql-data-test
      - nosql-data-test
      - identity-api-test
      - rabbitmq-test
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests

  payment-api-test:
    image: ${REGISTRY:-eshop}/payment-api-test:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile
    depends_on:
      - rabbitmq-test

  locations-api-functional-test:
    image: ${REGISTRY:-eshop}/locations-api-test:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Location/Locations.API/Dockerfile
      target: functionaltest
    depends_on:
      - nosql-data-test
      - rabbitmq-test
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests